### ISSUE TITLE
Memory leak in game client

### ISSUE THREAD

**Issue by ferib** [AnimeShooter/QServer#2]
The `14/03/2012` binary has a memory leak related to some particles not being freed after use.

Such particles are generated from the Wiper, Flashbang, and other throwing weapons, the game will run out of memory at around 2GB of memory, causing the game to crash. Before crashing a noticeable FPS drop builds up.

Currently, there is no fix, I recommend you restart your game after a few hours of player or until noticeable FPS builds up. _(doubt anyone plays this long, #wontfix)_

**Comment by kuroppoi** [comment]
This is probably a bit late and no longer relevant, but I would like to share what I know about this.

From what I remember, a very low amount of memory (17,000 bytes) was allocated for the particle vertex buffer. Whenever the buffer ran out of space, any new particles would be put in a queue to be rendered later. This is also where I believe the memory leak happens; in a scenario where a lot of particles had to be rendered, the game would enqueue new particles faster than it could clear buffer space.

A while ago I made [a patch](https://github.com/kuroppoi/grand-qpang-archive/blob/master/Patches/20120314/increase_particle_limit.1337) that increases the vertex buffer space by a substantial amount so that it could support a lot of snow particles for the Christmas plaza map, and it also seemed to get rid of the memory leak as I saw no memory increase even after running the game for an entire day.

**Comment by ferib** [comment]
Hey, thanks for the info! I remember looking into it myself and only getting to the point where I noticed the Wiper bomb would spawn particles. These details (and patches) could be interesting for the https://github.com/AnimeShooter/QPangMiniLauncher project. I used the mini launcher to patch out the anti-hack shield and skip the loading screen, so if you are here for hacktober you can PR the changes. (or not and let me know so I will do it).

Also, the latest version of the game we could find had this bug fixed, but the network protocol was changed.

**Comment by kuroppoi** [comment]
I could make a PR, but the patch is aimed at On3D.dll and not the QPang binary, so it would require a little bit of fiddling.

**Comment by Slyvan25** [comment]
i mean if the On3D.dll is patched you could just send it through the updater/tell people to replace that file. the Qpang community isn't that big anymore

**Comment by ferib** [comment]
The qpang community is nonexisting, and from my experience, they don't like it when you send modified files (signature no longer valid), hence why Project AnimeShooter sticks to using installer + open-source patcher

**Comment by kuroppoi** [comment]
Yeah feel free. I'll leave it to you, then.

**Comment by ferib** [comment]
> Yeah feel free. I'll leave it to you, then.

My pleasure!

> Also, the latest version of the game we could find had this bug fixed, but the network protocol was changed.

Come to think of it, we might be able to just take the On3D.dll from the latest game so we don't have to patch anything and don't invalidate code signatures 🤔

**Comment by ferib** [comment]
Closing due to https://github.com/AnimeShooter/QPangMiniLauncher/pull/2
